### ISSUE TITLE
Unable to push schema changes using GitHub Actions

### ISSUE THREAD

**Issue by MichielS-1848709** [planetscale/cli#549]
Hey! I want to automate the process of pushing changes to the database schemas. Locally this script is running fine, however using GitHub Actions I get an error message.

I'm using the supplied helper scripts to run this job.

**Script**
```bash
. use-pscale-docker-image.sh
. authenticate-ps.sh
. set-db-and-org-and-branch-name.sh
. wait-for-branch-readiness.sh

cd ../../../packages/server/prisma

pscale connect <org> development --org <org> --execute-protocol=mysql --execute="yarn run prisma db push"
```

**Expected output**
The expected output would be that this pushes my changes to the changed schemas. Locally this works fine, however, GitHub Actions throws the following error in debug mode:

![image](https://user-images.githubusercontent.com/32015956/186623147-3a9eb2ab-8e83-4cd7-a246-2ae6727b8487.png)

For some reason, I need to authenticate. I don't understand why since I'm already authenticated.

I also tried some mutations of the command:
```bash
...
pscale connect <org> development --org <org> --port 3306 &
cd ../../../packages/server/prisma &&
ls -l &&
export DATABASE_URL="mysql://root@127.0.0.1:3306/<org>" &&
yarn run prisma db push
```
However, this resulted in the same issue. Any help is welcome.

**EDIT**
Some additional information, a piece of the GitHub Action
```yaml
...
      - name: Create database - please click on displayed link to authenticate
        timeout-minutes: 3
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{secrets.PLANETSCALE_SERVICE_TOKEN_ID}}
          PLANETSCALE_SERVICE_TOKEN: ${{secrets.PLANETSCALE_SERVICE_TOKEN}}
          ORG_NAME: <org>
          DB_NAME: <org>
          BRANCH_NAME: development
          GITHUB_USER: ${{github.actor}}
        working-directory: ./bin/database/planetscale
        run: |
          chmod +x create-deploy-request.sh
          ./create-deploy-request.sh
      - name: Done
        run: |
          echo "Done!"
          sleep 10
...
```
