### ISSUE TITLE
How to connect to the db from a ddev container (local env)?

### ISSUE THREAD

**Issue by palomamtnez** [planetscale/cli#629]
I am using Laravel for my app, and DDEV for my local container and development environment.
I would like to connect to my PlanetScale database but since this cli has 127.0.0.1 as host, but I am using DDEV to host the app instead, it doesn't work as expected.

**Comment by palomamtnez** [comment]
I am trying to add a service this way:

```
services:
  pscale:
    image: planetscale/pscale:latest
    container_name: "ddev-${DDEV_SITENAME}-pscale"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    expose:
      - "9999"
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=9998:9999
      - HTTPS_EXPOSE=9999:9999
```

However I get the error: 
 The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
