### ISSUE TITLE
`pscale auth login` does not do anything after confirming via browser, `--debug` flags does not show anything

### ISSUE THREAD

**Issue by mnpqraven** [planetscale/cli#651]
This is all i'm seeing after running `pscale auth login --debug`, the browser opens up but the CLI doesn't proceed after I confirm on the browser, I can't even Ctrl+C the process when during the 'waiting for confirmation...' loop nor do i see any extra info with the `--debug` flag
```
Confirmation Code: <code>

If something goes wrong, copy and paste this URL into your browser: https://auth.planetscale.com/oauth/device?user_code=<code>
Waiting for confirmation...
```

What's funny is that I'm running a dual boot with Windows and the CLI works without any problem when I'm using Windows so it's unlikely to be a network issue

My linux machine's info is as following: 
```
alacritty 0.12.0 (5a728195)
kernel      |  6.2.10-arch1-1
distro      |  Arch Linux
WM          |  LeftWM (X11)
shell       |  zsh
```
`state.yml`
```
checked_for_update_at: 2023-04-15T02:25:14.927572068+07:00
latest_release:
  version: v0.136.0
  url: https://github.com/planetscale/cli/releases/tag/v0.136.0
  publishedat: 2023-04-05T18:23:38Z
```
